# Generated by Django 3.2.7 on 2021-11-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='missedIngredientCount',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='usedIngredientCount',
        ),
    ]
